const savedNotesArray = require('../data/db');
const saveNewNote = require('../lib/notes');
const nanoid = require('nanoid');
const router = require('express').Router();



// route to read db.json file & return saved notes as json data
router.get('/db', (req, res) => {
    let results = savedNotesArray;

    if (req.query) {
        results = filterByQuery(req.query, results);
    }
    res.json(results);
});


// route to receive new note, save to request body, add it to db.json file & return new note to client
router.post('/db', (req, res) => {
    // give note object it's own unique id (generated by npm module 'nanoid')
    req.body.id = nanoid();
    // add new note object to json file and savedNotesArray 
    const newNote = saveNewNote(req.body, savedNotesArray);
    res.json(newNote);
});




module.exports = router;